name: Update JSON Mythic Dungeon

on:
  workflow_dispatch:

jobs:
  update_json_dungeon:
    name: Update JSON Dungeon
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: dungeon
        run: python generate_combo.py -d -m -r mythic ${{ secrets.RAIDBOTSAPI }}
      - name: commit
        run: |
          git config user.name Balance-SimC
          git config user.email Balance-SimC@github.com
          if [ -z "$(git status --porcelain)" ]; then
            echo "no updates to JSON"
          else
            git pull --rebase --autostash
            git add .
            git commit -m "update JSON Dungeon"
            git push
          fi
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: update_json3
          path: |
            *.json
