name: Update JSON (PTR)

on:
  workflow_dispatch:

jobs:
  update_json_ptr:
    name: Update JSON PTR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: one target
        run: python generate_combo_ptr.py -t 1 ${{ secrets.RAIDBOTSAPI }}
      - name: two targets
        run: python generate_combo_ptr.py -t 2 ${{ secrets.RAIDBOTSAPI }}
      - name: three targets
        run: python generate_combo_ptr.py -t 3 ${{ secrets.RAIDBOTSAPI }}
      - name: four targets
        run: python generate_combo_ptr.py -t 4 ${{ secrets.RAIDBOTSAPI }}
      - name: commit
        run: |
          git config user.name Balance-SimC
          git config user.email Balance-SimC@github.com
          if [ -z "$(git status --porcelain)" ]; then
            echo "no updates to JSON"
          else
            git pull --rebase --autostash
            git add .
            git commit -m "update JSON PTR"
            git push
          fi
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: update_json_ptr
          path: |
            *.json

  update_json_ptr2:
    name: Update JSON PTR 2
    needs: [ update_json_ptr ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: |
          python -m pip install --upgrade pip
          pip install requests      
      - name: five targets
        run: python generate_combo_ptr.py -t 5 ${{ secrets.RAIDBOTSAPI }}
      - name: spread
        run: python generate_combo_ptr.py -s ${{ secrets.RAIDBOTSAPI }}
      - name: one target move
        run: python generate_combo_ptr.py -t 1 -m ${{ secrets.RAIDBOTSAPI }}
      - name: commit
        run: |
          git config user.name Balance-SimC
          git config user.email Balance-SimC@github.com
          if [ -z "$(git status --porcelain)" ]; then
            echo "no updates to JSON"
          else
            git pull --rebase --autostash
            git add .
            git commit -m "update JSON PTR"
            git push
          fi
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: update_json_ptr2
          path: |
            *.json
  update_json_ptr3:
    name: Update JSON PTR 3
    needs: [ update_json_ptr2 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: dungeon
        run: python generate_combo_ptr.py -d -m ${{ secrets.RAIDBOTSAPI }}
      - name: commit
        run: |
          git config user.name Balance-SimC
          git config user.email Balance-SimC@github.com
          if [ -z "$(git status --porcelain)" ]; then
            echo "no updates to JSON"
          else
            git pull --rebase --autostash
            git add .
            git commit -m "update JSON PTR"
            git push
          fi
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: update_json_ptr3
          path: |
            *.json
