name: Update JSON Mythic

on:
  workflow_dispatch:

jobs:
  update_json_1t:
    name: Update JSON 1T
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: one target
        run: python generate_combo.py -t 1 -r mythic ${{ secrets.RAIDBOTSAPI }}
      - name: commit
        run: |
          git config user.name Balance-SimC
          git config user.email Balance-SimC@github.com
          if [ -z "$(git status --porcelain)" ]; then
            echo "no updates to JSON"
          else
            git pull --rebase --autostash
            git add .
            git commit -m "update JSON 1T"
            git push
          fi
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: update_json
          path: |
            *.json

  update_json_2t:
    name: Update JSON 2T
    needs: [ update_json_1t ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: two targets
        run: python generate_combo.py -t 2 -r mythic ${{ secrets.RAIDBOTSAPI }}
      - name: commit
        run: |
          git config user.name Balance-SimC
          git config user.email Balance-SimC@github.com
          if [ -z "$(git status --porcelain)" ]; then
            echo "no updates to JSON"
          else
            git pull --rebase --autostash
            git add .
            git commit -m "update JSON 2T"
            git push
          fi
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: update_json
          path: |
            *.json

  update_json_3t:
    name: Update JSON 3T
    needs: [ update_json_2t ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: three targets
        run: python generate_combo.py -t 3 -r mythic ${{ secrets.RAIDBOTSAPI }}
      - name: commit
        run: |
          git config user.name Balance-SimC
          git config user.email Balance-SimC@github.com
          if [ -z "$(git status --porcelain)" ]; then
            echo "no updates to JSON"
          else
            git pull --rebase --autostash
            git add .
            git commit -m "update JSON 3T"
            git push
          fi
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: update_json
          path: |
            *.json

  update_json_4t:
    name: Update JSON 4T
    needs: [ update_json_3t ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: four targets
        run: python generate_combo.py -t 4 -r mythic ${{ secrets.RAIDBOTSAPI }}
      - name: commit
        run: |
          git config user.name Balance-SimC
          git config user.email Balance-SimC@github.com
          if [ -z "$(git status --porcelain)" ]; then
            echo "no updates to JSON"
          else
            git pull --rebase --autostash
            git add .
            git commit -m "update JSON 4T"
            git push
          fi
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: update_json
          path: |
            *.json

  update_json_5t:
    name: Update JSON 5T
    needs: [ update_json_4t ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: four targets
        run: python generate_combo.py -t 5 -r mythic ${{ secrets.RAIDBOTSAPI }}
      - name: commit
        run: |
          git config user.name Balance-SimC
          git config user.email Balance-SimC@github.com
          if [ -z "$(git status --porcelain)" ]; then
            echo "no updates to JSON"
          else
            git pull --rebase --autostash
            git add .
            git commit -m "update JSON 5T"
            git push
          fi
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: update_json
          path: |
            *.json

  update_json_10t:
    name: Update JSON 10T
    needs: [ update_json_4t ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: four targets
        run: python generate_combo.py -t 10 -r mythic ${{ secrets.RAIDBOTSAPI }}
      - name: commit
        run: |
          git config user.name Balance-SimC
          git config user.email Balance-SimC@github.com
          if [ -z "$(git status --porcelain)" ]; then
            echo "no updates to JSON"
          else
            git pull --rebase --autostash
            git add .
            git commit -m "update JSON 10T"
            git push
          fi
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: update_json
          path: |
            *.json

  update_json_spread:
    name: Update JSON Spread
    needs: [ update_json_10t ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: |
          python -m pip install --upgrade pip
          pip install requests      
      - name: one target move
        run: python generate_combo.py -t 1 -m -r mythic ${{ secrets.RAIDBOTSAPI }}
      - name: commit
        run: |
          git config user.name Balance-SimC
          git config user.email Balance-SimC@github.com
          if [ -z "$(git status --porcelain)" ]; then
            echo "no updates to JSON"
          else
            git pull --rebase --autostash
            git add .
            git commit -m "update JSON Spread"
            git push
          fi
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: update_json2
          path: |
            *.json
            
  update_json_move:
    name: Update JSON Move
    needs: [ update_json_spread ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: |
          python -m pip install --upgrade pip
          pip install requests      
      - name: one target move
        run: python generate_combo.py -t 1 -m -r mythic ${{ secrets.RAIDBOTSAPI }}
      - name: commit
        run: |
          git config user.name Balance-SimC
          git config user.email Balance-SimC@github.com
          if [ -z "$(git status --porcelain)" ]; then
            echo "no updates to JSON"
          else
            git pull --rebase --autostash
            git add .
            git commit -m "update JSON Move"
            git push
          fi
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: update_json2
          path: |
            *.json
            
  update_json_dungeon:
    name: Update JSON Dungeon
    needs: [ update_json_move ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: dungeon
        run: python generate_combo.py -d -m -r mythic ${{ secrets.RAIDBOTSAPI }}
      - name: commit
        run: |
          git config user.name Balance-SimC
          git config user.email Balance-SimC@github.com
          if [ -z "$(git status --porcelain)" ]; then
            echo "no updates to JSON"
          else
            git pull --rebase --autostash
            git add .
            git commit -m "update JSON Dungeon"
            git push
          fi
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: update_json3
          path: |
            *.json
            
  update_talents:
    name: Update Talent Sims
    needs: [ update_json_dungeon ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: update python
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: talent sims
        run: python generate_by_talent.py -r mythic ${{ secrets.RAIDBOTSAPI }}
      - name: commit
        run: |
          git config user.name Balance-SimC
          git config user.email Balance-SimC@github.com
          if [ -z "$(git status --porcelain)" ]; then
            echo "no updates to talent sims"
          else
            git pull --rebase --autostash
            git add .
            git commit -m "update talent sims"
            git push
          fi
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: update_talents
          path: |
            by_talent.html
            jso.js
